name: Deploy to Harmon Web (FTP)

on:
  push:
    branches:
      - main # Change this to your primary branch name (e.g., master)

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: Arkinox # This tells GitHub to look inside your "Arkinox" environment for secrets
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 🔨 Install dependencies & Build
        run: |
          npm install
          npm run build

      - name: 🚀 Sync Files to Harmon Web
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # Adding the passphrase for your new key
          port: 22
          source: "dist/*"
          target: "public_html"
          strip_components: 1
